# GitHub Pages Configuration
# This file configures how GitHub Pages serves your site

# Security headers
headers:
  - "/*":
      - "X-Frame-Options: DENY"
      - "X-Content-Type-Options: nosniff"
      - "X-XSS-Protection: 1; mode=block"
      - "Referrer-Policy: strict-origin-when-cross-origin"
      - "Content-Security-Policy: upgrade-insecure-requests"
  
  - "/assets/*":
      - "Cache-Control: public, max-age=31536000, immutable"
  
  - "*.js":
      - "Content-Type: application/javascript"
  
  - "*.css":
      - "Content-Type: text/css"
  
  - "*.html":
      - "Content-Type: text/html"
  
  - "*.svg":
      - "Content-Type: image/svg+xml"

# Redirects for SPA
redirects:
  - from: "/*"
    to: "/index.html"
    status: 200

# MIME types
mime_types:
  js: application/javascript
  css: text/css
  html: text/html
  svg: image/svg+xml 